Associations
kaitcham/school_library pull request #3
Opened 2022-06-15 13:31 UTC by kaitcham

For this branch, I followed these [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_associations.md)

**Required Changes**
- A method which implements the has-many side of the relationship between the Person and Rental

2022-06-15 13:51 UTC, t-yanick requested changes
Hi @kaitcham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-15 13:51 UTC, t-yanick commented on classroom.rb
> +end
- [ ] To implement the `belong-to` side of the relationship between `Student` and `Classroom`, a method that serves as the 'belongs-to' side (a student belongs to a classroom) should be implemented in the `Student` class. Checkout this [link](`https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships`)  for clarifications. Something like so: 
```ruby
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
```

2022-06-15 13:51 UTC, t-yanick commented on rental.rb
> +    person.rental.push(self) unless person.rental.includes?(self)
- [ ] To implement the `has-many` side of the relationship between `Person` and `Rental`, a method that serves as the 'has-many' side (a person has many rentals) should be implemented in the `Person` class. Checkout this [link](`https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship`) for clarifications. Something like so: 
```ruby
  def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2022-06-15 13:51 UTC, t-yanick commented on rental.rb
> +  attr_reader :book, :person
- [ ] Please kindly set `setters` for `@book and @person` instance variables, are they are modifies within the `Rental` class. Something like so: 
```
attr_accessor  :book, :person
```

2022-06-16 07:37 UTC, sja-thedude commented on rental.rb
> +  attr_reader :book, :person
Implemented 👍

2022-06-16 07:37 UTC, sja-thedude commented on classroom.rb
> +end
Implemented 👍

2022-06-16 08:09 UTC, Meltrust approved these changes
Hi @kaitcham,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Thank you for updating your person class, as requested✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-17 06:05 UTC, merged